# Generated by Django 4.2.5 on 2023-09-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authtoken", "0003_tokenproxy"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringToken",
            fields=[
                (
                    "token_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authtoken.token",
                    ),
                ),
                ("expiration_time", models.DateTimeField(blank=True, null=True)),
            ],
            bases=("authtoken.token",),
        ),
    ]
